import type { Metadata } from 'next';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import Toolbar from '@mui/material/Toolbar';
import LayoutFrame from '@/layouts/LayoutFrame';
import { DrawerWidth } from '@/constants';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Box sx={{ display: 'flex' }}>
          <CssBaseline />
          <LayoutFrame />
          <Box
            component="main"
            sx={{
              flexGrow: 1,
              p: 2,
              width: { sm: `calc(100% - ${DrawerWidth}px)` },
            }}
          >
            <Toolbar />
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
